### ISSUE TITLE
User Credentials for GitHub Action

### ISSUE THREAD

**Issue by sorenarchibald** [Qbizinc/sandbox-data-pipeline#14]
From what I read, the current _Best Practice_ is to use _Open ID Connect_ (OIDC) as a means for GitHub to send a token, which will identify itself to AWS.  A role must be added to AWS for GitHub to assume.  The role will have specific polices, giving GitHub the ability to push and tag images to the _Elastic Container Repository_.  I found the following documents very helpful to setup the Identity and Policy.

1. [Configuring OpenID Connect in Amazon Web Services](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)
2. [Creating and managing an OIDC provider (console)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
3. [Required IAM permissions for pushing an image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html)
4. [Required IAM permissions for pushing an image](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service)

**Comment by sorenarchibald** [comment]
I've added the IAM Provider [token.actions.githubusercontent.com](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/identity_providers/details/OPENID/arn%3Aaws%3Aiam%3A%3A907770664110%3Aoidc-provider%2Ftoken.actions.githubusercontent.com).  Looking for ways to test.

**Comment by qbiz-nate-fritter** [comment]
PR in #11 has been merged. There is now a deployment file [here](https://github.com/Qbizinc/sandbox-data-pipeline/blob/main/.github/workflows/ecs-deploy-scheduled.yml) that is scheduled to deploy a container to Amazon ECS at 11:30am PT every day. 

We should see if this workflow successfully works shortly.

**Comment by sorenarchibald** [comment]
Merged and working.
