### ISSUE TITLE
Add Snowflake equivalent of "CURRENT_TIMESTAMP" to Snowflake tables

### ISSUE THREAD

**Issue by njfritter** [Qbizinc/sandbox-data-pipeline#9]
The BigQuery tables in the sandbox data pipeline capture the timestamp that the data was written to the table using the built in `CURRENT_TIMESTAMP` function (code example [here](https://github.com/Qbizinc/sandbox-data-pipeline/blob/main/dags/sql/write_cocktails_to_bigquery.sql#L57)).

However, the corresponding Snowflake tables do not have an equivalent implemented (Snowflake SQL code [here](https://github.com/Qbizinc/sandbox-data-pipeline/blob/main/dags/sql/write_cocktails_to_snowflake.sql)).

This should be implemented in Snowflake for the following reasons:
1. Achieve greater parity between Snowflake and BigQuery tables
2. Allow for Anomalo checks on Snowflake tables to be run "upon arrival" rather than at a specific time of day in order to match the configurations of the Anomalo checks on the BigQuery tables.

[This built in Snowflake function](https://docs.snowflake.com/en/sql-reference/functions/current_timestamp) should be sufficient.

Screenshots attached showing difference in Anomalo configurations.

![Image](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/0fce4fb8-c5e2-4e21-bd4b-2d025bcb9e67)
![Image](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/d3374cec-e8be-483d-a134-ef54f26379e8)

**Comment by sorenarchibald** [comment]
Updated `create table` on weather table so the column will exist if we need to rebuild the schema.  I then preformed the following SQL to update the existing table:

```
use schema SANDBOX_DATA_PIPELINE.public;

create table if not exists weather_temp
(
    run_hr      int,
    location_name string,
    local_time   timestamp,
    temp_c      int,
    temp_f      int,
    is_day      boolean,
    condition   variant,
    wind_kph    float,
    wind_mph    float,
    gust_kph    float,
    gust_mph    float,
    pressure_mb int,
    pressure_in int,
    humidity    int,
    cloud       int,
    feelslike_c int,
    feelslike_f int,
    vis_km      int,
    vis_miles   int,
    uv          int,
    created_at_ts  timestamp default CURRENT_TIMESTAMP
);

insert into weather_temp select *, CURRENT_TIMESTAMP from weather;

ALTER TABLE WEATHER RENAME TO WEATHER_ORG;
ALTER TABLE WEATHER_TEMP RENAME TO WEATHER;

select count(*) from weather;
select * from weather;

update weather set created_at_ts = null;
drop table weather_org;
```
